"""Grid world and pathfinding primitives."""

from stage0_sim.domain.economy import TransactionPoint
from stage0_sim.domain.world.city import (
    Building,
    BuildingEntrance,
    BuildingPortal,
    CityBounds,
    CityWorld,
    CityZone,
    District,
    MapPoint,
    OutdoorPlace,
    Room,
    SpatialScale,
    TransportEdge,
    TransportNode,
    TravelLeg,
    TravelMode,
    TravelStatus,
    Vehicle,
    VehicleRegistry,
    VehicleState,
    WorldLocation,
    WorldObject,
    find_transport_route,
)
from stage0_sim.domain.world.model import (
    AffordanceAction,
    AffordanceStation,
    Coordinate,
    HomeostasisEffect,
    WorldGrid,
    WorldMap,
    Zone,
    default_affordance_action,
)
from stage0_sim.domain.world.pathfinding import find_path
from stage0_sim.domain.world.routing import (
    NavigationPlanningError,
    RecursiveRoutePlanner,
)
from stage0_sim.domain.world.topology import (
    LocalRoute,
    Locator,
    Route,
    RouteLeg,
    Space,
    SpaceRegistry,
    SpaceTopology,
    TopologyView,
    Transition,
    TraversalContext,
)
from stage0_sim.domain.world.topology_adapters import (
    ContainerTopology,
    GridTopology,
    SparseGraphTopology,
)

__all__ = [
    "AffordanceAction",
    "AffordanceStation",
    "Building",
    "BuildingEntrance",
    "BuildingPortal",
    "CityBounds",
    "CityZone",
    "CityWorld",
    "ContainerTopology",
    "Coordinate",
    "District",
    "HomeostasisEffect",
    "GridTopology",
    "LocalRoute",
    "Locator",
    "MapPoint",
    "NavigationPlanningError",
    "OutdoorPlace",
    "Room",
    "RecursiveRoutePlanner",
    "Route",
    "RouteLeg",
    "Space",
    "SpaceRegistry",
    "SpaceTopology",
    "SpatialScale",
    "SparseGraphTopology",
    "TopologyView",
    "TransportEdge",
    "TransportNode",
    "TransactionPoint",
    "Transition",
    "TraversalContext",
    "TravelLeg",
    "TravelMode",
    "TravelStatus",
    "Vehicle",
    "VehicleRegistry",
    "VehicleState",
    "WorldGrid",
    "WorldMap",
    "WorldObject",
    "WorldLocation",
    "Zone",
    "default_affordance_action",
    "find_path",
    "find_transport_route",
]
